# Generated by Django 5.0.7 on 2024-08-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_author_date_of_birth_and_more'),
        ('catalog', '0002_bookinstance_borrower_alter_bookinstance_status_and_more'),
    ]

    operations = [
    ]
